#
# # Define path to the desired wallpaper picture
# $wallpaper_1 = ~/Pictures/wallpapers/thedarkrealm.png
# $wallpaper_2 = /home/purple/Pictures/wallpapers/redtrees.jpg
# $wallpaper_3 = /home/purple/Pictures/wallpapers/calendar.png
# # $wallpaper_4 = ~/Pictures/wallpapers/
# # $wallpaper_5 = ~/Pictures/wallpapers/
# # $wallpaper_6 = ~/Pictures/wallpapers/
# # $wallpaper_7 = ~/Pictures/wallpapers/
#
#
# # Choose current wallpaper
# $current = $wallpaper_3
#
# preload = $current              # Loads the image
# wallpaper =, $current           # Displays the loaded image
#
# # wallpaper = monitor, contain: /home/  .png    # Contain or Tile
# # Monitor DP-2
#
#
# # Enable IPC for 0.53+ compatibility
# ipc = true
#
# # Use absolute paths or reliable ~ paths
# $w1 = ~/Pictures/wallpapers/thedarkrealm.png
# $w2 = ~/Pictures/wallpapers/redtrees.jpg
# $w3 = /home/purple/Pictures/wallpapers/calendar.png
#
# # The new logic: Preload is still required for the config file
# preload = $w3
#
# # Note the syntax: monitor,path (no space after comma for best compatibility)
# wallpaper = HDMI-A-1,$w3
#
# # Recommended: Disable splash text for a cleaner look
splash = false



wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/calendar.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/calendar.png
    fit_mode = cover
}
