# # System
# exec-once = waybar & hyprpaper & swaync & hypridle & nm-applet & nextcloud &
# exec-once = fcitx5 --replace &
#
# # Workspace 1
# exec-once  = hyprctl dispatch workspace 1 && kitty &
#
# # Workspace 2
# exec-once = sleep 1 && hyprctl dispatch workspace 2 && zen-browser && notion-app &
#
# # Workspace 3 (defined in window-rules)
# exec-once = discord & spotify & # spotube &
#
# # Workspace 4 (defined in window-rules)
# exec-once = steam &
#
# # Workspace 5
# exec-once = sleep 5s && hyprctl dispatch workspace 5 && vscode # /usr/share/pycharm/bin/pycharm &
#

# 1. Environment & Core Services (Crucial for 0.53)
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar & hyprpaper & swaync & hypridle & nm-applet & nextcloud &
exec-once = fcitx5 --replace &

exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] zen-browser
exec-once = [workspace 2 silent] notion-app
exec-once = [workspace 3 silent] discord
exec-once = [workspace 3 silent] spotify
exec-once = [workspace 4 silent] steam
exec-once = [workspace 5 silent] code
